create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name text unique not null,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.point_events (
  id bigint generated by default as identity primary key,
  player_name text not null references public.players(name),
  action text not null,
  points integer not null,
  created_at timestamptz not null default now()
);

insert into public.players (name) values
  ('Παναοτ'), ('Νικ'), ('Κατσα'), ('Πλιοκας'), ('Τολης'), ('Θάνος')
on conflict (name) do nothing;

alter table public.players enable row level security;
alter table public.point_events enable row level security;

drop policy if exists "public can read players" on public.players;
drop policy if exists "public can read point events" on public.point_events;
drop policy if exists "public can insert point events" on public.point_events;

create policy "public can read players" on public.players for select using (true);
create policy "public can read point events" on public.point_events for select using (true);
create policy "public can insert point events" on public.point_events
  for insert
  with check (
    exists (select 1 from public.players where public.players.name = player_name)
    and points between -10 and 50
    and length(trim(action)) > 0
  );
